// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB48sXIhZIb7xOc4F6i5QJMZCnXLFScvic',
    appId: '1:637108089897:web:691794d32dffd78962d838',
    messagingSenderId: '637108089897',
    projectId: 'login-45cfc',
    authDomain: 'login-45cfc.firebaseapp.com',
    storageBucket: 'login-45cfc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzySnoNOmK24884VauZjwHNmCVoHrpklo',
    appId: '1:637108089897:android:90bab239b9dc443b62d838',
    messagingSenderId: '637108089897',
    projectId: 'login-45cfc',
    storageBucket: 'login-45cfc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFz7N0qp1glPJuVvp0mrgsDry2TQKBUQA',
    appId: '1:637108089897:ios:39606d4f55ee5d6a62d838',
    messagingSenderId: '637108089897',
    projectId: 'login-45cfc',
    storageBucket: 'login-45cfc.appspot.com',
    iosBundleId: 'com.example.firebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFz7N0qp1glPJuVvp0mrgsDry2TQKBUQA',
    appId: '1:637108089897:ios:75e64a37949bed6b62d838',
    messagingSenderId: '637108089897',
    projectId: 'login-45cfc',
    storageBucket: 'login-45cfc.appspot.com',
    iosBundleId: 'com.example.firebaseLogin.RunnerTests',
  );
}
