// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfe1zmsBurOfE4ZowXdRGzbl6_giWW0vM',
    appId: '1:83978990241:web:c1b7000e93ce5e0c0c36e0',
    messagingSenderId: '83978990241',
    projectId: 'todo-21fd5',
    authDomain: 'todo-21fd5.firebaseapp.com',
    storageBucket: 'todo-21fd5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZqJnhYpSmd8--OctUhiFwT6eB-rOpw2o',
    appId: '1:83978990241:android:04effe6bbb3db25a0c36e0',
    messagingSenderId: '83978990241',
    projectId: 'todo-21fd5',
    storageBucket: 'todo-21fd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8CIf-SRXqkGKCjVdUjFdM-AS0aRyFTto',
    appId: '1:83978990241:ios:8ccd2d8cc64a114a0c36e0',
    messagingSenderId: '83978990241',
    projectId: 'todo-21fd5',
    storageBucket: 'todo-21fd5.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8CIf-SRXqkGKCjVdUjFdM-AS0aRyFTto',
    appId: '1:83978990241:ios:0a7f6ce8497ef2d60c36e0',
    messagingSenderId: '83978990241',
    projectId: 'todo-21fd5',
    storageBucket: 'todo-21fd5.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
