// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvltRlAv6D447EgwKaZG1iBzP9Atnb6hU',
    appId: '1:494846215095:web:a4a67920abfa22dd6a1e32',
    messagingSenderId: '494846215095',
    projectId: 'crudoperations-ef9c6',
    authDomain: 'crudoperations-ef9c6.firebaseapp.com',
    storageBucket: 'crudoperations-ef9c6.appspot.com',
    measurementId: 'G-BPXH1JGN54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlMy2IB2L1KO6Fkxwrh51I8DgJorEGC1Y',
    appId: '1:494846215095:android:0ccf6762558a0a8f6a1e32',
    messagingSenderId: '494846215095',
    projectId: 'crudoperations-ef9c6',
    storageBucket: 'crudoperations-ef9c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRfNtb69kAVgZCvteIPD3BjIOszZU6iOQ',
    appId: '1:494846215095:ios:4bd84e643436eb536a1e32',
    messagingSenderId: '494846215095',
    projectId: 'crudoperations-ef9c6',
    storageBucket: 'crudoperations-ef9c6.appspot.com',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRfNtb69kAVgZCvteIPD3BjIOszZU6iOQ',
    appId: '1:494846215095:ios:68663700aafac5fd6a1e32',
    messagingSenderId: '494846215095',
    projectId: 'crudoperations-ef9c6',
    storageBucket: 'crudoperations-ef9c6.appspot.com',
    iosBundleId: 'com.example.firebaseCrud.RunnerTests',
  );
}
